version: 2

sources:
  - name: gz_raw_data
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      
      - name: raw_gz_product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: the id that is uniquely identifies the product
            tests:
              - unique
              - not_null
          - name: purchase_cost
            description: the purchase cost is the multiplication of quantity and purchase price

      - name: raw_gz_sales
        identifier: raw_gz_sales
        description: sales of greenweez
        tests:
              - unique:
                  column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: the number that uniquely identifies the order(primary key)
          - name: products_id
            description: the number that uniquely identifies the product
          - name: revenue
            description: the amount of money earned from each selling
          - name: quantity
            description: the quantity of each product in each order

      - name: raw_gz_ship
        identifier: raw_gz_ship
        description: shipping data for greenweez
        columns:
          - name: orders_id
            description: the number that correspondes to each order in sales table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the charge for delivering the order
          - name: logcost
            description: the expense incurred in the process of transporting goods
          - name: ship_cost
            description: the cost of shipping the order     


      - name: raw_gz_adwords
        identifier: raw_gz_adwords
        description: adwords
        tests:
        - unique:
            column_name: "(date_date || '-' ||  campaign_key)"
        columns:
          - name: date_date
            description: the date of the campaign 
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name  
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click  


      - name: raw_gz_bing
        identifier: raw_gz_bing
        description: bing
        tests:
        - unique:
            column_name: "(date_date || '-' ||  campaign_key)"
        columns:
          - name: date_date
            description: the date of the campaign 
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name  
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click  



      - name: raw_gz_criteo
        identifier: raw_gz_criteo
        description: criteo
        tests:
        - unique:
            column_name: "(date_date || '-' ||  campaign_key)"
        columns:
          - name: date_date
            description: the date of the campaign 
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name  
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click  


      - name: raw_gz_facebook
        identifier: raw_gz_facebook
        description: facebook
        tests:
        - unique:
            column_name: "(date_date || '-' ||  campaign_key)"
        columns:
          - name: date_date
            description: the date of the campaign 
          - name: paid_source
            description: paid source
          - name: campaign_key
            description: campaign_key
          - name: camPGN_name
            description: camPGN_name  
          - name: ads_cost
            description: ads_cost
          - name: impression
            description: impression
          - name: click
            description: click  



      # - name: int_campaign
      #   description: data from all campaigns
      #   tests:
      #     - unique:
      #         column_name: "date_date || '-' || campaign_key)"
      #     - not_null:
      #         column_name:
      #           - paid_source
      #           - campaign_name
      #   columns:
      #     - name: date_date
      #       description: the date of the campaign 
      #     - name: paid_source
      #       description: paid source
      #     - name: campaign_key
      #       description: campaign_key
      #     - name: camPGN_name
      #       description: camPGN_name  
      #     - name: ads_cost
      #       description: ads_cost
      #     - name: impression
      #       description: impression
      #     - name: click
      #       description: click  

    
      - name: finance_campaigns_day
        description: global kpi
        columns:
          - name: ads_margin
            description: operational_margin - ads_cost
          - name: average_basket
            description: average basket cost for each day 
        tests:
          - not_null:
              column_name:
                - ads_margin
                - average_basket

